site_name  : Wolf CMS documentation
site_url   : https://docs.wolfcms.org
site_author: The Wolf CMS team
copyright: Copyright 2015, Wolf CMS project.

repo_url: https://github.com/wolfcms/docs.wolfcms.org

theme: readthedocs

strict: true

pages:
    - Introduction: 'index.md'
    - Getting started:
        - Requirements: 'getting-started/requirements.md'
        - Installation: 'getting-started/installation.md'
        - Configuration: 'getting-started/configuration.md'
    - Admin guide:
        - Clean URLs: 'admin-guide/rewrite.md'
    - Development:
        - The Observer System: 'development/observer-system.md'
        - Helpers: 'development/helpers.md'
        - Functions: 'development/functions.md'
        - Constants: 'development/constants.md'
    - About:
        - FAQ: 'faq.md'
        - Glossary: 'glossary.md'
        - Styleguide: 'styleguide.md'

markdown_extensions: [abbr,attr_list,def_list,footnotes,tables,admonition,nl2br,toc]
